### ISSUE TITLE
Isnt runnning on Linux

### ISSUE THREAD

**Issue by zgast** [mgerdes/minigolf#5]
Thats the errors

System:
Ubuntu 21.04
dwm/xorg

![image](https://user-images.githubusercontent.com/65947021/160075007-966b6d03-afca-48e4-966e-32dd7c1fa625.png)

**Comment by drhodes** [comment]
Try running from the project root directory:

`Open-Golf $ ./out/linux/editor`

**Comment by mgerdes** [comment]
Yes, try what drhodes suggested and it should work. I could probably detect this and give a better error message in the future though.
